# Generated by Django 4.0.5 on 2022-06-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='feeeeeeeeeeeee',
            field=models.CharField(default='', max_length=200),
        ),
    ]
