# Generated by Django 4.0.5 on 2022-06-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_feeeeeeeeeeeee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='feeeeeeeeeeeee',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
