# Generated by Django 4.0.5 on 2022-06-19 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryname', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='UserAdvance',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='advance', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ipaddr', models.CharField(max_length=15)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useradvance', to='almanac.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useradvance', to='almanac.country')),
            ],
        ),
        migrations.CreateModel(
            name='MarketDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField()),
                ('finishdate', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=400)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markday', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HolidayCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=400)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidaycountry', to='almanac.country')),
            ],
        ),
        migrations.CreateModel(
            name='HolidayCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=400)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday', to='almanac.city')),
            ],
        ),
    ]
